name: news-alert
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: install libs
        run: pip install feedparser requests
      - name: run
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python news_alert.py
